//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeDefective.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_defective_data
    {
        public int trans_no { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string entry_user { get; set; }
        public string update_user { get; set; }
        public string job_order_no { get; set; }
        public string lot_no { get; set; }
        public string wc { get; set; }
        public string machine_no { get; set; }
        public string shift { get; set; }
        public string process { get; set; }
        public string mold { get; set; }
        public Nullable<int> mold_set { get; set; }
        public string item { get; set; }
        public string defective_name { get; set; }
        public Nullable<int> defective_type { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> curing_qty { get; set; }
        public Nullable<int> cavity_qty { get; set; }
        public Nullable<int> no { get; set; }
        public Nullable<int> key_cycle { get; set; }
        public Nullable<int> good_qty { get; set; }
        public string curing_date { get; set; }
        public string prod_code { get; set; }
        public string curing_user { get; set; }
        public Nullable<double> master_def_by_fg { get; set; }
        public Nullable<double> def_by_fg { get; set; }
        public Nullable<int> result_by_fg { get; set; }
        public Nullable<double> master_def_by_wc { get; set; }
        public Nullable<double> def_by_wc { get; set; }
        public Nullable<int> result_by_wc { get; set; }
        public Nullable<double> master_def_by_type { get; set; }
        public Nullable<double> def_by_type { get; set; }
        public Nullable<int> result_by_type { get; set; }
        public Nullable<double> master_def_by_job { get; set; }
        public Nullable<double> def_by_job { get; set; }
        public Nullable<int> result_by_job { get; set; }
        public Nullable<double> master_def_by_cure_date { get; set; }
        public Nullable<double> def_by_cure_date { get; set; }
        public Nullable<int> result_by_cure_date { get; set; }
        public Nullable<double> master_def_by_item { get; set; }
        public Nullable<double> def_by_item { get; set; }
        public Nullable<int> result_by_item { get; set; }
        public string location_cd { get; set; }
        public string wc_process { get; set; }
        public string machine_no_process { get; set; }
        public string start_curing_date { get; set; }
        public string eng_code { get; set; }
    }
}
