//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeDefective.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_defective_item
    {
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string entry_user { get; set; }
        public string update_user { get; set; }
        public string location_cd { get; set; }
        public Nullable<double> defective_rate { get; set; }
        public string item { get; set; }
    }
}
