//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeDefective.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_master_item
    {
        public string wc { get; set; }
        public string wc_name { get; set; }
        public string item_code { get; set; }
        public string item_description { get; set; }
        public string product_code { get; set; }
        public string product_code_name { get; set; }
        public string unit { get; set; }
        public string source_type { get; set; }
        public string eng_code { get; set; }
    }
}
